-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 19:14:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laczenie_ludzi_poprzez_pasje
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laczenie_ludzi_poprzez_pasje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laczenie_ludzi_poprzez_pasje` DEFAULT CHARACTER SET utf8 ;
USE `laczenie_ludzi_poprzez_pasje` ;

-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`User` (
  `idUser` INT NOT NULL COMMENT 'unique id, different for each user',
  `name` VARCHAR(45) NULL COMMENT 'Name of the user',
  `surname` VARCHAR(45) NULL COMMENT 'Surname of the user',
  `dateOfBirth` DATETIME NULL COMMENT 'Date of birth of the user',
  `city` VARCHAR(45) NULL COMMENT 'city where user lives',
  `email` VARCHAR(60) NULL COMMENT 'actual email of the user',
  `password` VARCHAR(45) NULL COMMENT 'password of the user',
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`Host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`Host` (
  `idHost` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'name of the host',
  `surname` VARCHAR(45) NULL COMMENT 'surname of the host\n',
  PRIMARY KEY (`idHost`),
  UNIQUE INDEX `idHost_UNIQUE` (`idHost` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`Location` (
  `idLocation` INT NOT NULL,
  `location` VARCHAR(45) NULL COMMENT 'Name of the street and city',
  `locationName` VARCHAR(45) NULL COMMENT '\"nickname\" of the location',
  `category` VARCHAR(45) NULL COMMENT 'category of the activity which you can do in this place',
  `subCategory` VARCHAR(45) NULL COMMENT 'sub category of this activity ',
  `timeStart` DATETIME NULL COMMENT 'date when you can start \"renting\" this loction ',
  `timeEnd` DATETIME NULL COMMENT 'date when you must leave the place',
  `numberOfPeople` INT NULL COMMENT 'number of people which will be in this place',
  `Host_idHost` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `Host_idHost`),
  INDEX `fk_Location_Host1_idx` (`Host_idHost` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Host1`
    FOREIGN KEY (`Host_idHost`)
    REFERENCES `laczenie_ludzi_poprzez_pasje`.`Host` (`idHost`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`Activity` (
  `idActivity` INT NOT NULL COMMENT 'unique id, different for each activity',
  `name` VARCHAR(45) NULL COMMENT 'name of the activity',
  `category` VARCHAR(45) NULL COMMENT 'category of the activity',
  `subCategory` VARCHAR(45) NULL COMMENT 'subcategory of the category',
  PRIMARY KEY (`idActivity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`Connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`Connection` (
  `idConnection` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'name of the connection between activity and location',
  `date` DATETIME NULL COMMENT 'date of the connection',
  `additionalInfo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'additional information about this connection (could be NULL)',
  `Location_idLocation` INT NOT NULL,
  `Location_Host_idHost` INT NOT NULL,
  `Activity_idActivity` INT NOT NULL,
  PRIMARY KEY (`idConnection`, `Location_idLocation`, `Location_Host_idHost`, `Activity_idActivity`),
  INDEX `fk_Connection_Location1_idx` (`Location_idLocation` ASC, `Location_Host_idHost` ASC) VISIBLE,
  INDEX `fk_Connection_Activity1_idx` (`Activity_idActivity` ASC) VISIBLE,
  CONSTRAINT `fk_Connection_Location1`
    FOREIGN KEY (`Location_idLocation` , `Location_Host_idHost`)
    REFERENCES `laczenie_ludzi_poprzez_pasje`.`Location` (`idLocation` , `Host_idHost`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Connection_Activity1`
    FOREIGN KEY (`Activity_idActivity`)
    REFERENCES `laczenie_ludzi_poprzez_pasje`.`Activity` (`idActivity`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`Connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`Connections` (
  `idConnections` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Connection_idConnection` INT NOT NULL,
  PRIMARY KEY (`idConnections`, `User_idUser`, `Connection_idConnection`),
  INDEX `fk_Connections_User_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Connections_Connection1_idx` (`Connection_idConnection` ASC) VISIBLE,
  CONSTRAINT `fk_Connections_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `laczenie_ludzi_poprzez_pasje`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Connections_Connection1`
    FOREIGN KEY (`Connection_idConnection`)
    REFERENCES `laczenie_ludzi_poprzez_pasje`.`Connection` (`idConnection`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laczenie_ludzi_poprzez_pasje`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laczenie_ludzi_poprzez_pasje`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
